repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: pretty-format-json
        args: [--autofix]
    -   id: check-added-large-files
        args: [--maxkb, '50000']
    -   id: check-ast
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [--ignore, "E501,W503,E203,E266"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort
        language: python
        args: ["--profile", "black"]
